import { NextApiRequest, NextApiResponse } from 'next';

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method !== 'GET') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { id } = req.query;
  
  if (!id || typeof id !== 'string') {
    return res.status(400).json({ error: 'Invalid resume ID' });
  }
  
  try {
    // Generate plain text resume content based on ID
    const resumeText = generateResumeText(id);

    // Set response headers for text file download
    res.setHeader('Content-Type', 'text/plain');
    res.setHeader('Content-Disposition', `attachment; filename="resume_${id}.txt"`);
    
    // Send the text content
    res.send(resumeText);
  } catch (error: any) {
    console.error(`Error serving resume for ID ${id}:`, error);
    return res.status(500).json({ error: error.message || 'Something went wrong' });
  }
}

// Helper function to generate resume text
function generateResumeText(id: string): string {
  const isSweta = id === '1';
  
  return `
==============================================
RESUME - ${isSweta ? 'Sweta Sona' : `Applicant ${id}`}
==============================================

PERSONAL INFORMATION
-------------------
Name: ${isSweta ? 'Sweta Sona' : `Applicant ${id}`}
Email: ${isSweta ? 'swetasona@gmail.com' : `applicant${id}@example.com`}
Phone: ${isSweta ? '9823873268' : `555-123-456${id}`}
Location: ${isSweta ? 'Jamshedpur, India' : 'City, Country'}

EDUCATION
--------
${isSweta ? 
'Degree: Bachelor of Technology in Computer Science\n' +
'Institution: XYZ University\n' +
'Year: 2019-2023' 
: 
'Degree: Degree in Subject\n' +
'Institution: University Name\n' +
'Year: 20XX-20XX'}

EXPERIENCE
---------
${isSweta ? 
'Position: Software Developer\n' +
'Company: Tech Solutions Inc.\n' +
'Duration: 2023-Present\n' +
'- Developed web applications using React and Node.js\n' +
'- Implemented CI/CD pipelines for automated testing and deployment\n' +
'- Collaborated with cross-functional teams to deliver features on time' 
: 
'Position: Position Title\n' +
'Company: Company Name\n' +
'Duration: Date Range\n' +
'- Accomplishment 1\n' +
'- Accomplishment 2\n' +
'- Accomplishment 3'}

SKILLS
-----
${isSweta ? 
'JavaScript, TypeScript, React, Node.js, Next.js, SQL, Git, CI/CD, Agile' 
: 
'Skill 1, Skill 2, Skill 3, Skill 4, Skill 5'}

PROJECTS
-------
${isSweta ? 
'Project: E-commerce Platform\n' +
'- Built a full-stack e-commerce platform using MERN stack\n' +
'- Implemented payment gateway integration and order management system\n\n' +
'Project: Portfolio Website\n' +
'- Designed and developed a personal portfolio website using Next.js and Tailwind CSS' 
: 
'Project: Project 1\n' +
'- Description of project 1\n\n' +
'Project: Project 2\n' +
'- Description of project 2'}

==============================================
Generated by Talnurt Recruitment Portal
==============================================
`.trim();
} 